source 'http://rubygems.org'

gem 'rails', '3.2.17'
gem 'sqlite3'
gem 'therubyracer'
gem 'json'
gem 'nokogiri'
gem 'jquery-rails'
gem 'daemons'
gem 'isaac', :require => 'isaac/bot'
gem 'eventmachine'
gem 'later_dude'
gem 'rails_autolink'
gem 'pry'
gem 'pry-rails'
gem 'rails-i18n'
gem 'russian'
gem 'unicorn'
gem 'thin'
gem 'devise'
gem 'cancan'
gem 'markitup-rails'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'rmagick'
gem 'hirb'
gem 'capistrano'
gem 'paperclip'
gem 'bcrypt-ruby'
gem 'jbuilder'

group :assets do
  gem 'sass'
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development do
  gem 'better_errors', '~> 1.1.0'
  gem 'rails-erd'
  gem 'meta_request'
  gem 'binding_of_caller'
  gem 'guard-livereload'
  gem 'rack-livereload'
end
