:server: irc.tomsk.net
:port: 6666
:nick: sagax_keeper
:channels:
    - "#rails"
    - "#webdev"
    - "#vim"
    - "#defrag"
    - "#help"
    - "#ircrubot"
    - "#javascript"
    - "#opensuse"
    - "#python"
    - "#ruby"
    - "#slax"
    - "#tcl"
    - "#linux"
    - "#ffmpeg"
    - "#xmonad"
    - "#gvim"
    - "#event"
    - "#events"
    - "#todo"
    - "#golang"
